name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9' # Replace with your Flutter version

    - name: Install dependencies
      run: flutter pub get
    
    - name: Set environment variables
      run: echo "ENV_SECRET_INFO=$ENV_SECRET_INFO" > .env

    - name: Build APK
      run: flutter build apk
      env:
        ENV_SECRET_INFO: ${{ secrets.ENV_SECRET_INFO }}

    - name: Deploy to Firebase App Distribution
      uses: w9jds/firebase-action@v2
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: internal
        file: build/app/outputs/flutter-apk/app-release.apk