name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9' # Replace with your Flutter version

    - name: Install dependencies
      run: flutter pub get
    
    - name: Set environment variables
      run: echo "ENV_SECRET_INFO=$ENV_SECRET_INFO" > .env

    - name: Build APK
      run: flutter build apk
      env:
        ENV_SECRET_INFO: ${{ secrets.ENV_SECRET_INFO }}
   
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/build/outputs/apk/release/app-release.apk